//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Words.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Words.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNotes_Lock_closed_highlight {
            get {
                object obj = ResourceManager.GetObject("btnNotes_Lock_closed_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNotes_Lock_closed_idle {
            get {
                object obj = ResourceManager.GetObject("btnNotes_Lock_closed_idle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNotes_Lock_open_highlight {
            get {
                object obj = ResourceManager.GetObject("btnNotes_Lock_open_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNotes_Lock_open_idle {
            get {
                object obj = ResourceManager.GetObject("btnNotes_Lock_open_idle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNotes_MainScreen {
            get {
                object obj = ResourceManager.GetObject("btnNotes_MainScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNotes_MainScreen_Highlight {
            get {
                object obj = ResourceManager.GetObject("btnNotes_MainScreen_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Align_Center {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Align_Center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Align_Center_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Align_Center_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Align_Left {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Align_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Align_Left_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Align_Left_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Align_Right {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Align_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Align_Right_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Align_Right_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_CopyCutter {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_CopyCutter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_CopyCutter_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_CopyCutter_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_File_Load {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_File_Load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_File_Load_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_File_Load_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_File_New {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_File_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_File_New_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_File_New_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_File_Save {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_File_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_File_Save_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_File_Save_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_File_SaveAs {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_File_SaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_File_SaveAs_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_File_SaveAs_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_FindWord {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_FindWord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_FindWord__Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_FindWord__Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Font_Bold {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Font_Bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Font_Bold_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Font_Bold_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Font_Italic {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Font_Italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Font_Italic_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Font_Italic_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Font_Strikeout {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Font_Strikeout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Font_Strikeout_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Font_Strikeout_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Font_Underline {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Font_Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Font_Underline_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Font_Underline_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_FontDecrease {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_FontDecrease", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_FontDecrease_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_FontDecrease_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_FontIncrease {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_FontIncrease", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_FontIncrease_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_FontIncrease_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_HighLighter_Dull {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_HighLighter_Dull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_HighLighter_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_HighLighter_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_LexiconEditor {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_LexiconEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_LexiconEditor_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_LexiconEditor_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Lock {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Lock_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Lock_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Picture_Insert {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Picture_Insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Picture_Insert_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Picture_Insert_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Redo {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Redo_Disabled {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Redo_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Redo_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Redo_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_SpellChecker {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_SpellChecker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_SpellChecker_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_SpellChecker_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_SubScript {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_SubScript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_SubScript_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_SubScript_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_SuperScript {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_SuperScript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_SuperScript_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_SuperScript_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Thesaurus {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Thesaurus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Thesaurus_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Thesaurus_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_ToolTip_Toggle {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_ToolTip_Toggle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_ToolTip_Toggle_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_ToolTip_Toggle_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Undo {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Undo_Disabled {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Undo_Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ck_RichTextBox_Button_Undo_Highlight {
            get {
                object obj = ResourceManager.GetObject("ck_RichTextBox_Button_Undo_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cursor_Capitalize {
            get {
                object obj = ResourceManager.GetObject("cursor_Capitalize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_Collapse {
            get {
                object obj = ResourceManager.GetObject("Cursor_Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_Expand {
            get {
                object obj = ResourceManager.GetObject("Cursor_Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_Garbage {
            get {
                object obj = ResourceManager.GetObject("Cursor_Garbage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_InsertWord {
            get {
                object obj = ResourceManager.GetObject("Cursor_InsertWord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cursor_MoveWord_Left {
            get {
                object obj = ResourceManager.GetObject("cursor_MoveWord_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cursor_MoveWord_Right {
            get {
                object obj = ResourceManager.GetObject("cursor_MoveWord_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_RecallWord {
            get {
                object obj = ResourceManager.GetObject("Cursor_RecallWord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_Selector_Both {
            get {
                object obj = ResourceManager.GetObject("Cursor_Selector_Both", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_Selector_Content {
            get {
                object obj = ResourceManager.GetObject("Cursor_Selector_Content", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_Selector_Heading {
            get {
                object obj = ResourceManager.GetObject("Cursor_Selector_Heading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cursor_Selector_None {
            get {
                object obj = ResourceManager.GetObject("Cursor_Selector_None", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dictionary {
            get {
                object obj = ResourceManager.GetObject("Dictionary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DictionarySelection {
            get {
                object obj = ResourceManager.GetObject("DictionarySelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap formBusy {
            get {
                object obj = ResourceManager.GetObject("formBusy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Keyboard_BLANK {
            get {
                object obj = ResourceManager.GetObject("Keyboard_BLANK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MagnifyingGlass_100pix {
            get {
                object obj = ResourceManager.GetObject("MagnifyingGlass_100pix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Main_Editor {
            get {
                object obj = ResourceManager.GetObject("Main_Editor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Add {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Add_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Add_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Collapse {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Collapse_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Collapse_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Down {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Down_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Down_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_EditMain {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_EditMain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_EditMain_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_EditMain_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Enum {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Enum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Enum_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Enum_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Expand {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Expand_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Expand_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_FileValid_False {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_FileValid_False", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_FileValid_False_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_FileValid_False_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_FileValid_True {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_FileValid_True", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_FileValid_True_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_FileValid_True_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Project {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Project", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Project_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Project_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Sub {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Sub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Sub_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Sub_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Up {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotePilot_Button_Up_Highlight {
            get {
                object obj = ResourceManager.GetObject("NotePilot_Button_Up_Highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Notes {
            get {
                object obj = ResourceManager.GetObject("Notes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Search_Text {
            get {
                object obj = ResourceManager.GetObject("Search_Text", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Selection {
            get {
                object obj = ResourceManager.GetObject("Selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Words {
            get {
                object obj = ResourceManager.GetObject("Words", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
